#!/bin/bash
set -e

ROOT="/root/hyper-factory"
cd "$ROOT" 2>/dev/null || {
  echo "❌ لا يمكن الدخول إلى $ROOT"
  exit 1
}

echo "🛠 Hyper Factory – Fix structural gaps"
echo "📍 ROOT = $ROOT"
echo "======================================"

# دالة مساعدة لضمان وجود مجلد
ensure_dir() {
  local d="$1"
  if [ -d "$d" ]; then
    echo "✅ DIR موجود: $d"
  else
    mkdir -p "$d"
    echo "➕ تم إنشاء DIR: $d"
  fi
}

# دالة مساعدة لملف مع إنشاء بسيط إذا لم يكن موجودًا
ensure_file() {
  local f="$1"
  local content="$2"
  if [ -f "$f" ]; then
    echo "✅ FILE موجود: $f"
  else
    echo -e "$content" > "$f"
    echo "➕ تم إنشاء FILE: $f"
  fi
}

echo
echo "1) Data Lakehouse / Catalog"
echo "---------------------------"

ensure_dir "data_lakehouse"
for zone in raw cleansed semantic serving catalog; do
  ensure_dir "data_lakehouse/$zone"
done

# README بسيط للـ catalog
ensure_file "data_lakehouse/catalog/README.md" \
"# Data Lakehouse Catalog

This directory stores schemas, table definitions, and metadata
for the Hyper Factory data lakehouse.
"

echo
echo "2) Workers skeleton"
echo "-------------------"

ensure_dir "workers"

for w in ingestor processor analyzer reporter; do
  ensure_dir "workers/$w"
  ensure_file "workers/$w/README.md" \
"# Worker: $w

This directory holds configs, runbooks, and artifacts
for the '$w' worker in the Hyper Factory pipeline.
"
done

echo
echo "3) Advanced Agents – missing engines"
echo "------------------------------------"

ensure_dir "agents"

create_agent_skeleton() {
  local name="$1"
  local nice_name="$2"
  local purpose="$3"

  ensure_dir "agents/$name"

  ensure_file "agents/$name/__init__.py" \
"# $name agent package
# Placeholder for advanced agent: $nice_name
"

  ensure_file "agents/$name/README.md" \
"# Agent: $nice_name

ID: $name

Purpose:
$purpose

Status:
- Skeleton created by hf_fix_gaps.sh
"

  ensure_file "agents/$name/config.yaml" \
"# Config for agent: $name
enabled: false
mode: skeleton
"

  ensure_file "agents/$name/main.py" \
"#!/usr/bin/env python3
\"\"\"Main entrypoint for agent: $name ($nice_name).

This is a skeleton implementation generated by hf_fix_gaps.sh.
\"\"\"

def run():
    print(\"[${name}] skeleton agent – no real logic yet.\")


if __name__ == \"__main__\":
    run()
"
  chmod +x "agents/$name/main.py"
}

# patterns_engine
create_agent_skeleton \
  "patterns_engine" \
  "Patterns Engine" \
  "- اكتشاف الأنماط المتكررة في البيانات\n- تغذية system_patterns في قاعدة المعرفة"

# quality_engine
create_agent_skeleton \
  "quality_engine" \
  "Quality Engine" \
  "- تقييم جودة البيانات والمخرجات\n- كتابة مؤشرات في knowledge_index / system_patterns"

# temporal_memory
create_agent_skeleton \
  "temporal_memory" \
  "Temporal Memory Engine" \
  "- إدارة agent_memory / الذاكرة الزمنية\n- تتبع تطور المعرفة والعمال مع الزمن"

# integration_hub
create_agent_skeleton \
  "integration_hub" \
  "Integration Hub" \
  "- إدارة التكامل مع الأنظمة الخارجية\n- استخدام integrations/* مثل github_api, notifications"

echo
echo "4) Optional: AI temporal memory folders"
echo "---------------------------------------"

ensure_dir "ai/memory"
ensure_dir "ai/memory/temporal"
ensure_file "ai/memory/temporal/README.md" \
"# Temporal Memory

This folder is reserved for time-based memory snapshots and
agent_memory exports from the knowledge database.
"

echo
echo "5) Re-run advanced audit (if available)"
echo "---------------------------------------"

if [ -x "./advanced_audit.py" ]; then
  echo "🚀 تشغيل advanced_audit.py بعد الإصلاح..."
  python3 advanced_audit.py || echo "⚠️ advanced_audit.py فشل، تحقّق يدويًا."
else
  echo "ℹ️ advanced_audit.py غير موجود أو غير قابل للتنفيذ – تخطّي."
fi

echo
echo "✅ hf_fix_gaps.sh – اكتمل تنفيذ سكربت إصلاح الفجوات."
